### PR TITLE
Fix serial sampler not to set agent inputs to None.

### PR DESCRIPTION
**Pull request by neighthan**
`collector.reset_if_needed` modifies `agent_inputs` in place but doesn't return anything, so the return value should not be assigned to `agent_inputs`. The alternative fix would be to have `collector.reset_if_needed` return `agent_inputs`, but I think it's clearer that the modification is in-place if nothing is returned.

(here's the fixed PR for this one, on a separate branch; sorry for the mess in the last one)

### CODE REVIEW

**Comment by astooke** [comment]
Yes good point, and it looks like the `reset_if_needed` ended up always operating in-place on `agent_inputs`. 
Want to go into samplers.base.py and change the signature of the base `reset_if_needed` to `pass`?  Combine that into this pull request and will accept :)

**Comment by neighthan** [comment]
Ah, good catch on the base class. I've updated that one now, so it should be good to go.

**Comment by neighthan** [comment]
A quick grep revealed `samplers/parallel_worker.py` also assigned to the return from a `reset_if_needed` call. I don't see anything else that does this assignment now or that returns from this function.

**Comment by astooke** [comment]
Good catch, thanks!!

**Pull request merged**
