### PR TITLE
Support hierarchical naming scheme to avoid cluttering the UI in TensorBoard

### PR DESCRIPTION
**Pull request by juliusfrost**
The previous naming scheme for the logging summaries made cluttered tabs in tensorboard. I added a simple forward slash to make subcategory summaries grouped together.
image

### CODE REVIEW

**Comment by astooke** [comment]
Hey this looks great!

Ok one recent change, take a look at latest commit 8ca1819 which gets rid of the annoying `group_slash` kwarg and just does it automatically when using a `tf_summary_writer`.  Seeing this PR made me realize to do that :)  Want to simplify this PR on top of that?

**Comment by juliusfrost** [comment]
Yeah, that looks great!

**Comment by juliusfrost** [comment]
I removed the group_slash kwarg as you suggested. Let me know if there is anything else before merging!

**Comment by astooke** [comment]
OK actually I just noticed this handy context manager in the logger:

https://github.com/astooke/rlpyt/blob/8f36bda2ddc57c5d828eea0d69569f325cb8dc88/rlpyt/utils/logging/logger.py#L240

Looks like it would make it easier to add/remove other fields as people wish.

However it might also require adding the prefix to the summary writer line of `record_tabular`:

https://github.com/astooke/rlpyt/blob/8f36bda2ddc57c5d828eea0d69569f325cb8dc88/rlpyt/utils/logging/logger.py#L215

Sorry to extend the work here but I think this could make it nice and clean.  What do you think about wrapping the multiple `logger.record_tabular()` calls with the tabular prefix context manager?  And then probably doing the `super().log_diagnostics()` call outside the context manager, presuming it will have its own?

**Comment by juliusfrost** [comment]
I'm not really sure how to do that, but you can modify this PR as you see fit!

**Comment by astooke** [comment]
OK thanks for the access.  Take a look at that commit and see if it seems to do the same thing you wanted?

**Comment by astooke** [comment]
Hey look at that...your test caught my typo  :)

**Comment by juliusfrost** [comment]
Cool! I verified it works in TensorBoard

**Pull request merged**
