### PR TITLE
Tensorboard

### PR DESCRIPTION
**Pull request by AlexanderKoch-Koch**
add tensorboard logging

-set iteration in logger from runner
-log to tensorboard record_tabular if SummaryWriter is not None
-change log names to enable grouping in tensorboard

### CODE REVIEW

**Comment by astooke** [comment]
Hey this looks great, thanks!  Let me just check what the effect is of adding the forward slash on the usual logger+viskit workflow.  Looks nice to group by prefix.

**Comment by astooke** [comment]
Hey sorry I'm just getting back to this...can you please share a small example script which does a training run and logs using tensorboard, so I can run it with your PR and look at the results in viskit?

**Comment by AlexanderKoch-Koch** [comment]
Hi, I've just added tensorboard logging by default now. So every example that uses logger_context should now log to tensorboard. It uses the exp_dir as directory for the SummaryWriter.
The SummaryWriter is included in torch.utils.tensorboard.writer. However, if you want to see the results, you have to pip install tensorboard as far as I know.
Start it with: tensorboard --logdir=path/to/exp_dir

**Comment by astooke** [comment]
OK cool thanks!  That all looks really good.

I just modified your PR to leave it backward compatible....summary writer disabled by default (kwarg into `logger_context()`) and slash character off by default (kwarg into `record_tabular_mist_stat()`), easy enough to set those default kwargs to `True` in your copy and go from there?  Or another suggestion to make that more seamless?

**Pull request merged**
