### PR TITLE
Issue #58 #61 Fix: Bug Fix & Perf. Optimize

### PR DESCRIPTION
**Pull request by wangwwno1**
Fix UnboundLocalError caused by variable typo in PrioritizedSequenceReplay.sample_batch

### CODE REVIEW

**Comment by wangwwno1** [comment]
Fix Issue #61 IndexError in SumTree.sample when unique=True

**Comment by astooke** [comment]
Thanks for all the finds!

All looks good except that not all algos have a `min_itr_learn`.  Maybe change those to `getattr(self.algo, "min_itr_learn", 0)`?  And then good to go and I'll merge.

**Comment by wangwwno1** [comment]
> Thanks for all the finds!
> 
> All looks good except that not all algos have a `min_itr_learn`. Maybe change those to `getattr(self.algo, "min_itr_learn", 0)`? And then good to go and I'll merge.

Good point!
I fix it in new PR by add an new attribute `min_itr_learn` to `runner` class, that should be good enough unless someone want to change `algo` in the middle of training.

**Comment by astooke** [comment]
Thanks!

I think the `min_itr_learn` won't get saved to the runner like this, because `save__init__args` only looks for the local variables which are also input kwargs?  So I just pushed a slight modification there to be sure.

**Pull request merged**
